/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#494456",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#7a7488",
        "outline-variant": "#cbc3da",
        "surface-tint": "#6a23fb",
        "primary": "#4900be",
        "on-primary": "#ffffff",
        "primary-container": "#6311f4",
        "on-primary-container": "#d4c5ff",
        "inverse-primary": "#cebdff",
        "secondary": "#006a64",
        "on-secondary": "#ffffff",
        "secondary-container": "#61f6ea",
        "on-secondary-container": "#006f69",
        "tertiary": "#762404",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#963a1a",
        "on-tertiary-container": "#ffbfab",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e8ddff",
        "primary-fixed-dim": "#cebdff",
        "on-primary-fixed": "#20005e",
        "on-primary-fixed-variant": "#5100cf",
        "secondary-fixed": "#65f8ed",
        "secondary-fixed-dim": "#40dcd1",
        "on-secondary-fixed": "#00201e",
        "on-secondary-fixed-variant": "#00504b",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-tertiary-fixed": "#390b00",
        "on-tertiary-fixed-variant": "#7f2a0a",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "surface-subtle": "#FDFDFD",
        "border-base": "#E2E8F0",
        "ai-accent": "#E6F9F8",
        "data-blue": "#2563EB",
        "success-green": "#10B981",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-lg": "32px",
        "gutter": "24px",
        "unit": "4px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
