import { Router } from "express";

import authRoutes from "../modules/auth/auth.routes.js";
import subscriptionRoutes from "../modules/subscription/subscription.routes.js";
import restaurantRouter from "../modules/restaurant/restaurant.routes.js";
import outletRoutes from "../modules/outlet/outlet.routes.js";
import categoryRouter from "../modules/category/category.routes.js";
import menuItemRouter from "../modules/menuItem/menuItem.routes.js";
import variantRouter from "../modules/variant/variant.routes.js";
import addonRouter from "../modules/addon/addon.routes.js";
import inventoryRouter from "../modules/inventory/inventory.routes.js";
import customerRouter from "../modules/customer/customer.routes.js";
import orderRouter from "../modules/order/order.routes.js";
import paymentRouter from "../modules/payment/payment.routes.js";
import notificationRouter from "../modules/notification/notification.routes.js";
import analyticsRouter from "../modules/analytics/analytics.routes.js";
import webhookRouter from "../modules/webhook/webhook.routes.js";
import auditLogRouter from "../modules/auditLog/auditLog.routes.js";
import userRoutes from "../modules/user/user.routes.js";
import integrationRouter from "../modules/integration/integration.routes.js";
import couponRouter from "../modules/coupon/coupon.routes.js";
import publicRouter from "../modules/auth/public.routes.js";
import diningRouter from "../modules/order/dining.routes.js";
import kdsRouter from "../modules/order/kds.routes.js";
import billingRouter from "../modules/order/billing.routes.js";
import shiftRouter from "../modules/outlet/shift.routes.js";
import reservationRouter from "../modules/order/reservation.routes.js";
import diningAnalyticsRouter from "../modules/analytics/dining-analytics.routes.js";
import systemAdminRoutes from "../modules/systemAdmin/systemAdmin.routes.js";
import healthRoutes from "../modules/health/health.routes.js";
import aiCopilotRoutes from "../modules/aiCopilot/routes/aiCopilot.routes.js";
import helpRequestRouter from "../modules/helpRequest/helpRequest.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/system-admin", systemAdminRoutes);
router.use("/health", healthRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/help-requests", helpRequestRouter);
router.use("/restaurants", restaurantRouter);
router.use("/outlets", outletRoutes);
router.use("/categories", categoryRouter);
router.use("/menu-items", menuItemRouter);
router.use("/variants", variantRouter);
router.use("/addons", addonRouter);
router.use("/inventory", inventoryRouter);
router.use("/customers", customerRouter);
router.use("/orders", orderRouter);
router.use("/payments", paymentRouter);
router.use("/notifications", notificationRouter);
router.use("/analytics", analyticsRouter);
router.use("/webhooks", webhookRouter);
router.use("/audit-logs", auditLogRouter);
router.use("/users", userRoutes);
router.use("/integrations", integrationRouter);
router.use("/coupons", couponRouter);
router.use("/public", publicRouter);
router.use("/dining", diningRouter);
router.use("/kds", kdsRouter);
router.use("/billing", billingRouter);
router.use("/shifts", shiftRouter);
router.use("/reservations", reservationRouter);
router.use("/dining-analytics", diningAnalyticsRouter);
router.use("/ai-copilot", aiCopilotRoutes);

export default router;
